#executable = /home/kadamczewski/miniconda3/envs/BayesianNeuralNetwork/bin/python
executable =/home/kadamczewski/miniconda3/bin/python

#arguments =/home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/Generator_census_multi.py
#arguments =/home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/test_condMMD_Isolet.py
arguments =/home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/test_condMMD_covtype.py



var=gen_covtype_5000_1000_mb0.1_fin
#var=covtype_mijung_all_fin
error = clust/clust_err/$(var).$(Process).err
output = clust/clust_out/$(var).$(Process).out
log = clust/clust_log/$(var).$(Process).log
requirements = TARGET.CUDAGlobalMemoryMb > 20000
request_memory = 8040
request_cpus = 1
request_gpus = 1
queue 1

