#executable = /home/kadamczewski/miniconda3/envs/BayesianNeuralNetwork/bin/python
executable = /usr/bin/unbuffer

#arguments =/home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/Generator_census_multi.py
#arguments =/home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/test_condMMD_Isolet.py
#arguments =/home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/test_condMMD_Epileptic.py
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/test_condMMD_covtype.py
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/test_condMMD_Credit.py
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/test_condMMD_Census.py
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/test_condMMD_CervicalCancer.py
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/condMMD_binary_priv.py --dataset $(dataset)
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/condMMD_multicat.py --dataset $(dataset)
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/priv_condMMD_intrusion.py
#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/separate_generators_binary_priv_pretr_heter.py --dataset $(dataset)
arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/privacy/DPDR/code/single_generator_priv_all.py --dataset $(dataset) --private $(private)  --undersample $(undersample) --batch $(batch) --data_type $(data_type)






var=dpmerf_$(dataset)_private_$(private)_undersample_$(undersample)_batch_$(batch)_$(data_type)
#var=credit_mijung_all_fin_fuller
#var=census_mijung_all_right
#var=covtype_mijung_allnew
#var=isolet_mijung_all_fin_aver_right
#var=epileptic_mijung_all_fin
error = clust/clust_err/$(var).$(Process).err
output = clust/clust_out/$(var).$(Process).out
log = clust/clust_log/$(var).$(Process).log
requirements = TARGET.CUDAGlobalMemoryMb > 30000
#buffer_size = 1000
stream_output=True
request_memory = 8040
request_cpus = 1
request_gpus = 1

batch=0.5
data_type=generated
private=0

# dataset=adult
# undersample=0.4
# batch=0.1
# queue 1


dataset=census
num_features=`500 1000 2000 5000 10000 20000 50000`
undersample=0.4
batch=0.1
queue 1

# dataset=epileptic
# undersample =1
# queue 1
#
# dataset=credit
# undersample = 0.005
# queue 1
#
# dataset=cervical
# undersample =1
# queue 1
#
# dataset=isolet
# undersample =1
# queue 1
#
# dataset=covtype
# num_features="500 1000 2000 5000 10000 20000"
# undersample=0.03
# batch=1
# queue 1
#
# dataset=intrusion
# num_features="500 1000 2000 5000"
# undersample=0.3
# batch=0.03
# queue 1




